### ISSUE TITLE
critical regions

### ISSUE THREAD

**Issue by mvimercati** [a-p-jo/allocator#1]
Hi, what happens if a high priority task interrupts a lower priority task which is in the critical region?

https://github.com/a-p-jo/allocator/blob/e3d791e7a00394f250ebeb638bee65a2de44707e/allocator.c#L52

I suppose the high priority task will loop forever trying to acquire the spinlock... may be?

**Comment by a-p-jo** [comment]
Yes, you're right, because the code has no notions of 'priority'. This is flaw inherent to simple, DIY spin-locks. A lockfree redesign is probably possible, but it is unlikely that I will be able to commit that much time as I am now in law school (which is also why this response is nearly half a year later).
